### ISSUE TITLE
Crash Program - Regione Abruzzo - Gestione Errore nella chiamata a fseComunicazioneMetadati

### ISSUE THREAD

**Issue by marlagatta** [ministero-salute/it-fse-support#1099]
Salve. 

Nell'eseguire delle chiamate al servizio 
https://fseservicetest.sanita.finanze.it/FseInsServicesWeb/services/fseComunicazioneMetadati

per la regione RDE in sussidiarietà  Abruzzo,

si ottiene da diverse ore l'errore  in calce:

```
HTTP/1.1 500 Internal Server Error
Content-Type: multipart/related; boundary="----=_Part_7_1329183330.1729086914783"; start-info="text/xml"; type="application/xop+xml"; start="<rootpart@soapui.org>"
X-Backside-Transport: FAIL FAIL
Connection: close

<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/"><env:Body><env:Fault><faultcode>env:Server</faultcode><faultstring>Internal Error (from server)</faultstring></env:Fault></env:Body></env:Envelope>

```

Quel che intendiamo segnalare, comunque, oltre all'errore in se stesso, è la non correttezza del messaggio di fault,
poiché pur essendo il messaggio multipart, non contiene boundary nella response, 
e ciò causa un'eccezione nel nostro Client Axis2:

```
Caused by: org.apache.axiom.om.OMException: Mime parts not found. Stream ended while searching for the boundary
        at org.apache.axiom.attachments.Attachments.<init>(Attachments.java:238)
        at org.apache.axis2.builder.BuilderUtil.createAttachments(BuilderUtil.java:564)
        at org.apache.axis2.builder.BuilderUtil.createAttachmentsMap(BuilderUtil.java:515)
        at org.apache.axis2.builder.MIMEBuilder.processDocument(MIMEBuilder.java:41)
        at org.apache.axis2.transport.TransportUtils.createDocumentElement(TransportUtils.java:188)
        at org.apache.axis2.transport.TransportUtils.createSOAPMessage(TransportUtils.java:146)
        at org.apache.axis2.transport.TransportUtils.createSOAPMessage(TransportUtils.java:109)
        at org.apache.axis2.transport.TransportUtils.createSOAPMessage(TransportUtils.java:68)
        at org.apache.axis2.description.OutInAxisOperationClient.handleResponse(OutInAxisOperation.java:351)
        at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:456)
        at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:227)
        at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
        at org.apache.axis2.client.ServiceClient.sendReceive(ServiceClient.java:554)
        at org.apache.axis2.client.ServiceClient.sendReceive(ServiceClient.java:530)
```

Se la chiamata viene eseguita con SOAPUI, si ha l'errore in console
```
Wed Oct 16 15:40:04 CEST 2024:ERROR:javax.mail.MessagingException: Missing start boundary
   javax.mail.MessagingException: Missing start boundary
   	at javax.mail.internet.MimeMultipart.parsebm(MimeMultipart.java:713)
   	at javax.mail.internet.MimeMultipart.parse(MimeMultipart.java:383)
   	at javax.mail.internet.MimeMultipart.getCount(MimeMultipart.java:229)
   	at com.eviware.soapui.impl.wsdl.submit.transports.http.support.attachments.MultipartMessageSupport.<init>(MultipartMessageSupport.java:60)
   	at com.eviware.soapui.impl.wsdl.submit.transports.http.support.attachments.MimeMessageResponse.<init>(MimeMessageResponse.java:79)
   	at com.eviware.soapui.impl.wsdl.submit.transports.http.support.attachments.WsdlMimeMessageResponse.<init>(WsdlMimeMessageResponse.java:57)
   	at com.eviware.soapui.impl.wsdl.submit.filters.HttpPackagingResponseFilter.wsdlRequest(HttpPackagingResponseFilter.java:68)
   	at com.eviware.soapui.impl.wsdl.submit.filters.HttpPackagingResponseFilter.afterAbstractHttpResponse(HttpPackagingResponseFilter.java:49)
   	at com.eviware.soapui.impl.wsdl.submit.filters.AbstractRequestFilter.afterRequest(AbstractRequestFilter.java:64)
   	at com.eviware.soapui.impl.wsdl.submit.transports.http.HttpClientRequestTransport.sendRequest(HttpClientRequestTransport.java:277)
   	at com.eviware.soapui.impl.wsdl.WsdlSubmit.run(WsdlSubmit.java:120)
   	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
   	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
   	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
   	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
   	at java.base/java.lang.Thread.run(Thread.java:831)
   	

```

**Comment by g-maugeri-sogei** [comment]
Buonasera,
per indagare il problema ci serve il dump completo della request.

**Comment by vigliottim** [comment]
Buonasera,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Sarà possibile riaprirla nel caso in cui fosse necessario ulteriore supporto.
Grazie.
