### ISSUE TITLE
Crash Program - Creazione documento da Piemonte verso Basilicata: BLOCKING_ERROR

### ISSUE THREAD

**Issue by marco-volpe** [ministero-salute/it-fse-support#1125]
Buongiorno

riceviamo il seguente errore in fase di pubblicazione documento

```json
{
      "eventType": "PUBLICATION",
      "eventDate": "2024-10-21T16:10:41.942+02:00",
      "eventStatus": "SUCCESS",
      "identificativoDocumento": "2.16.840.1.113883.2.9.2.010.4.4^1729519841174",
      "subject": "PROVAX00X00X000Y^^^\u00262.16.840.1.113883.2.9.4.3.2\u0026ISO",
      "tipoAttivita": "CON",
      "organizzazione": "010",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.92f163d3c8^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "traceId": "fa30dba95dff9ba4",
      "issuer": "integrity:S1#010#REGIONEPIEMONTETEST",
      "expiringDate": "2025-10-21T16:10:41.954+02:00"
    },
    {
      "eventType": "SEND_TO_INI",
      "eventDate": "2024-10-21T16:10:42.867+02:00",
      "eventStatus": "BLOCKING_ERROR",
      "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSRegistryErrorCODE CONTEXT:Internal Error 9000",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.92f163d3c8^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "expiringDate": "2025-10-21T16:10:42.875+02:00"
    }
```

Restiamo a disposizione

**Comment by vigliottim** [comment]
Buonasera,
chiediamo gentilmente di effettuare un nuovo test e darci un riscontro.
Grazie.

**Comment by marco-volpe** [comment]
Buonasera

riprovato ora e la creazione è stata completata positivamente

Le altre operazioni vanno in errore causa timeout.

Restiamo a disposizione

**Comment by g-maugeri-sogei** [comment]
Buonasera,
potete effettuare un nuovo tentativo e indicarci  in caso d'errore i riferimenti delle transazioni che hanno read timeout?

**Comment by marco-volpe** [comment]
Buongiorno @g-maugeri-sogei 

abbiamo eseguito un  nuovo test di creazione con esito positivo

```json
 {
      "eventType": "PUBLICATION",
      "eventDate": "2024-10-25T15:40:15.474+02:00",
      "eventStatus": "SUCCESS",
      "identificativoDocumento": "2.16.840.1.113883.2.9.2.10.4.4^1729863614351",
      "subject": "PROVAX00X00X000Y^^^\u00262.16.840.1.113883.2.9.4.3.2\u0026ISO",
      "tipoAttivita": "CON",
      "organizzazione": "010",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.6dc66eae06^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "traceId": "a92800af916d1fa5",
      "issuer": "integrity:S1#010#REGIONEPIEMONTETEST",
      "expiringDate": "2025-10-25T15:40:15.487+02:00"
    },
    {
      "eventType": "SEND_TO_INI",
      "eventDate": "2024-10-25T15:40:23.450+02:00",
      "eventStatus": "SUCCESS",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.6dc66eae06^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "expiringDate": "2025-10-25T15:40:23.519+02:00"
    }
```

L'aggiornamento è andato in timeout

Sostituzione e cancellazione invece sono state completate

Restiamo a disposzione

**Comment by g-maugeri-sogei** [comment]
Buongiorno,
potete svolgere un nuovo tentativo. In caso d'errore potete indicarci il CF dell'assistito e il timestamp della transazione in errore?

**Comment by marco-volpe** [comment]
Buongiorno @g-maugeri-sogei 

questo il nuovo tentativo andato in errore sempre in aggiornamento per Timeout

```json
{
      "eventType": "PUBLICATION",
      "eventDate": "2024-10-29T10:01:38.138+01:00",
      "eventStatus": "SUCCESS",
      "identificativoDocumento": "2.16.840.1.113883.2.9.2.10.4.4^1730192496947",
      "subject": "PROVAX00X00X000Y^^^\u00262.16.840.1.113883.2.9.4.3.2\u0026ISO",
      "tipoAttivita": "CON",
      "organizzazione": "010",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.45f913b7a6^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "traceId": "6fa0d9e83f9256f4",
      "issuer": "integrity:S1#010#REGIONEPIEMONTETEST",
      "expiringDate": "2025-10-29T10:01:38.146+01:00"
    },
    {
      "eventType": "SEND_TO_INI",
      "eventDate": "2024-10-29T10:01:39.759+01:00",
      "eventStatus": "SUCCESS",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.45f913b7a6^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "expiringDate": "2025-10-29T10:01:39.772+01:00"
    }
```

```
10:01:53.507 [pool-1-thread-1] INFO  i.c.d.d.g.j.i.GTWServiceV1Impl - URL: https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1/documents/2.16.840.1.113883.2.9.2.10.4.4%5E1730192496947/metadata
java.net.SocketTimeoutException: Read timed out
```

Il CF dell'assistito è sempre **PRVPVT81E03F052W**

Resto a disposizione

**Comment by g-maugeri-sogei** [comment]
A che ora e' partita la richiesta di aggiornamento?
Sui log vedo una richiesta di comunicazione metadati alle 10.01:39 e poi una ricerca documenti alle 10:01:54 che completa alle 10:01:55.
Se la richiesta e' questa, a quanto e' impostato il read timeout del vostro client?

**Comment by marco-volpe** [comment]
Il timeout è impostato standard a 15 secondi, per tutti i test che stiamo eseguendo

**Comment by g-maugeri-sogei** [comment]
OK il valore del timeout coincide con quelli delle chiamate. Il servizio di aggiornamento e' sincrono, al momento in validazione  va oltre i 15 secondi. Proviamo a velocizzarlo, in attesa per completare i test potete aumentare i valori sui read timeout ?
Considerate che anche la cancellazione e' sincrona.

**Comment by marco-volpe** [comment]
Il timeout di ogni chiamata è di 30 secondi ed è standard per tutti i test che facciamo
Cosi come c'è un tempo di attesa di 15 secondi, anch'esso standard, tra la pubblicazione e la richiesta di status

**Comment by marco-volpe** [comment]
> OK il valore del timeout coincide con quelli delle chiamate. Il servizio di aggiornamento e' sincrono, al momento in validazione va oltre i 15 secondi. Proviamo a velocizzarlo, in attesa per completare i test potete aumentare i valori sui read timeout ? Considerate che anche la cancellazione e' sincrona.

Abbiamo fatto un test di aggiornamento portando il timeout a 60 secondi ricevendo questo nuovo errore 502

```json
{
  "type": "https://govway.org/handling-errors/502/InvalidResponse.html",
  "title": "InvalidResponse",
  "detail": "Invalid response received from the API Implementation",
  "status": "502"
}

```

Il documento pubblicato era il seguente

```json
 {
      "eventType": "PUBLICATION",
      "eventDate": "2024-10-29T10:41:06.105+01:00",
      "eventStatus": "SUCCESS",
      "identificativoDocumento": "2.16.840.1.113883.2.9.2.10.4.4^1730194864692",
      "subject": "PROVAX00X00X000Y^^^\u00262.16.840.1.113883.2.9.4.3.2\u0026ISO",
      "tipoAttivita": "CON",
      "organizzazione": "010",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.f34a021b69^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "traceId": "01169d1c1ecc947b",
      "issuer": "integrity:S1#010#REGIONEPIEMONTETEST",
      "expiringDate": "2025-10-29T10:41:06.140+01:00"
    },
    {
      "eventType": "SEND_TO_INI",
      "eventDate": "2024-10-29T10:41:07.113+01:00",
      "eventStatus": "SUCCESS",
      "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.97bb3fc5bee3032679f4f07419e04af6375baafa17024527a98ede920c6812ed.f34a021b69^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "expiringDate": "2025-10-29T10:41:07.290+01:00"
    }
```

**Comment by g-maugeri-sogei** [comment]
Il 502 e' provocato da un problema sul GTW. Stiamo indagando. I timeout in lettura sono correlati all'errore.

**Comment by amarconS** [comment]
Salve,
abbiamo riscontrato che in fase di aggiornamento la ricerca metadati verso la Basilicata va in OK ma la comunicazione metadati riceve un errore "Internal Error 9000" e la chiamata dura circa 2minuti. Continuiamo le analisi internamente. Intanto chiediamo alla Basilicata di verificare se vedono chiamate in entrata da parte del Piemonte. La chiamata ha come timestamp "29/10/2024 10:41:23,173000". @BasilicataCrashProgramFSE

**Comment by BasilicataCrashProgramFSE** [comment]
Buongiorno,

Dalle verifiche interne risultano:

- Due transazioni di comunicaMetadati: la prima alle 2024-10-29 10:41:06,411 , la seconda alle 2024-10-29 10:41:23
- Una transazione di ricerca: alle 2024-10-29 10:41:21,892 con la risposta verso 2024-10-29 10:41:22,866

Abbiamo verificato e simulato la ricerca con lo uniqueId=2.16.840.1.113883.2.9.2.10.4.4^1730194864692, il servizio ha risposto in meno di 1500 millisecondi. 

Potete gentilmente riprovare?
Grazie

**Comment by g-maugeri-sogei** [comment]
Potete verificare la chiamata:
```

**[10/29/24 10:41:23:243 CET] 00002df0 SystemOut     O 2024-10-29 10:41:23,242 ERROR - REQUEST**: <?xml version="1.0" encoding="UTF-8" standalone="yes"?><ComunicazioneMetadatiRi
chiesta xmlns="http://comunicazionemetadatirichiesta.xsd.fse.ini.finanze.it" xmlns:ns2="http://tipodaticomunicazionemetadati.xsd.fse.ini.finanze.it"><IdentificativoUtente>PR
OVAX00X00X000Y</IdentificativoUtente><IdentificativoOrganizzazione>010</IdentificativoOrganizzazione><DescrizioneOrganizzazione>Regione Piemonte</DescrizioneOrganizzazione><
StrutturaUtente>2.16.840.1.113883.2.9.4.1.3.1135360012</StrutturaUtente><RuoloUtente>AAS</RuoloUtente><ContestoOperativo>UPDATE</ContestoOperativo><TipoDocumento>11502-2</Ti
poDocumento><IdentificativoAssistito>PRVPVT81E03F052W</IdentificativoAssistito><PresaInCarico>true</PresaInCarico><TipoAttivita>UPDATE</TipoAttivita><ElencoCFAssistito><ns2:
CFAssistito><ns2:cf>PRVPVT81E03F052W</ns2:cf><ns2:attivo>1</ns2:attivo></ns2:CFAssistito></ElencoCFAssistito><Metadato><ns2:TipologiaStrutturaProdDoc>Ospedale</ns2:Tipologia
StrutturaProdDoc><ns2:IdentificativoOrgDoc>2.16.840.1.113883.2.9.2.10</ns2:IdentificativoOrgDoc><ns2:IdentificativoAssistito>PRVPVT81E03F052W</ns2:IdentificativoAssistito><n
s2:TipoMime>application/pdf+text/x-cda-r2+xml</ns2:TipoMime><ns2:LivelloConfidenzialita>N</ns2:LivelloConfidenzialita><ns2:IdentificativoRepository>2.16.840.1.113883.2.9.2.1
0.4.5.1</ns2:IdentificativoRepository><ns2:IdentificativoDocumento>2.16.840.1.113883.2.9.2.10.4.4^1730194864692</ns2:IdentificativoDocumento><ns2:TipologiaDocumentoAlto>REF<
/ns2:TipologiaDocumentoAlto><ns2:TipologiaDocumentoMedio>11502-2</ns2:TipologiaDocumentoMedio><ns2:TipologiaDocumentoBasso>2.16.840.1.113883.2.9.10.1.1</ns2:TipologiaDocumen
toBasso><ns2:RiferimentoDocumento>2.16.840.1.113883.2.9.2.10.4.4^1730194864692</ns2:RiferimentoDocumento><ns2:Associazione><ns2:associationType>urn:oasis:names:tc:ebxmlregre
p:AssociationType:HasMember</ns2:associationType><ns2:sourceObject>SubmissionSet1</ns2:sourceObject><ns2:targetObject>Document1</ns2:targetObject><ns2:submissionSetStatus>Or
iginal</ns2:submissionSetStatus><ns2:previousVersion>1</ns2:previousVersion></ns2:Associazione><ns2:IdentificativoUnivocoDocumento>Document1</ns2:IdentificativoUnivocoDocume
nto><ns2:VersioneOggettoDocumento>1</ns2:VersioneOggettoDocumento><ns2:DataValidazioneDocumento>20241029104106</ns2:DataValidazioneDocumento><ns2:RuoloAutore>AAS</ns2:RuoloA
utore><ns2:IstituzioneAutore>CLINICA PINNA PINTOR^^^^^&amp;2.16.840.1.113883.2.9.4.1.3&amp;ISO^^^^01135360012</ns2:IstituzioneAutore><ns2:CodiceFiscaleAutore>AAAAAA00B77B000
F^^^^^^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO</ns2:CodiceFiscaleAutore><ns2:SizeDoc>0</ns2:SizeDoc><ns2:AssettoOrganizzativo>AD_PSC001</ns2:AssettoOrganizzativo><ns2:Ide
ntificativoPaziente>PRVPVT81E03F052W^^^&amp;2.16.840.1.113883.2.9.4.3.2&amp;ISO</ns2:IdentificativoPaziente><ns2:TipoAttivitaClinica>CON</ns2:TipoAttivitaClinica><ns2:Lingua
Documento>it-IT</ns2:LinguaDocumento><ns2:DataInizioPrestazione>20241008110100</ns2:DataInizioPrestazione><ns2:DataFinePrestazione>20241008110100</ns2:DataFinePrestazione><n
s2:StatoDocumento>APPROVED</ns2:StatoDocumento><ns2:DataSottomissione>20241029094123</ns2:DataSottomissione><ns2:IdentificativoSottomissione>2.16.840.1.113883.2.9.2.10.4.3.1
730194881465</ns2:IdentificativoSottomissione></Metadato></ComunicazioneMetadatiRichiesta>

..........

**[10/29/24 10:43:23:272 CET] 00002df0 SystemOut     O 2024-10-29 10:43:23,272 ERROR - ### COMUNICA METADATI RICHIESTA: ERRORE: Internal Error**
[10/29/24 10:43:23:273 CET] 00002df0 SystemOut     O 2024-10-29 10:43:23,272 ERROR - Internal Error
javax.xml.ws.soap.SOAPFaultException: Internal Error
        at org.apache.axis2.jaxws.marshaller.impl.alt.MethodMarshallerUtils.createSystemException(MethodMarshallerUtils.java:1363)
        at org.apache.axis2.jaxws.marshaller.impl.alt.MethodMarshallerUtils.demarshalFaultResponse(MethodMarshallerUtils.java:1089)
        at org.apache.axis2.jaxws.marshaller.impl.alt.DocLitBareMinimalMethodMarshaller.demarshalFaultResponse(DocLitBareMinimalMethodMarshaller.java:442)
        at org.apache.axis2.jaxws.client.proxy.JAXWSProxyHandler.getFaultResponse(JAXWSProxyHandler.java:632)
       


```

**Comment by vigliottim** [comment]
Buonasera,
le facciamo presente che non si tratta di una prima creazione ma un aggiornamento metadati.
Le chiediamo gentilmente di verificare.
Grazie.

> Buongiorno,
> 
> Abbiamo verificato il caso, l'errore e relativo alla valorizzazione errata di del metadato RiferimentoDocumento nella ComunicazioneMetadatiRichiesta con il valore del uniqueId invece che uuid: **ns2:RiferimentoDocumento2.16.840.1.113883.2.9.2.10.4.4^1730194864692</ns2:RiferimentoDocumento>**
> 
> Essendo una nuova versione, ci aspettiamo la valorizzazione come segue: **ns2:IdentificativoDocumento2.16.840.1.113883.2.9.2.10.4.4^1730194864692</ns2:IdentificativoDocumento>** <**ns2:RiferimentoDocumento/>** non valorizzato per prima versione
> 
> A disposizione Grazie

**Comment by BasilicataCrashProgramFSE** [comment]
Buongiorno,

Abbiamo sistemato il problema. 
Potete gentilmente riprovare?

Grazie

**Comment by marco-volpe** [comment]
Buongiorno @BasilicataCrashProgramFSE 

confermo che ora l'aggiornamento funziona correttamente

Grazie

**Comment by vigliottim** [comment]
Grazie per il gentile feedback.
Chiudiamo la presente issue e rimaniamo a disposizione per altre richieste di supporto.
