### ISSUE TITLE
Crash Program - Bolzano vs Toscana

### ISSUE THREAD

**Issue by SonnyMate** [ministero-salute/it-fse-support#1246]
Abbiamo un errore sulla creazione chiediamo un chiarimento:

        {
            "eventType": "PUBLICATION",
            "eventDate": "2024-11-11T16:09:55.796+01:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.41.4.4^IKIS-LAB-PDFCDA2_000000000102",
            "subject": "PSCRNI82B64A952I^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "ERP",
            "organizzazione": "041",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.41201.4.4.1.bbdd04c8a791124a7a6dc03455718b896ac55eb7f114e73e4c39ae6b6be5d69c.1869179c5f^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "d860f25926832239",
            "issuer": "integrity:S2#041#PABOLZANOTEST",
            "expiringDate": "2025-11-11T16:09:55.804+01:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-11-11T16:10:59.123+01:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSRegistryErrorCODE CONTEXT:Parallel processing failed for number 0. Exchange[ID-rt-sanita-tc11-s1-rtpc-sct-toscana-it-46740-1731335979206-2-30]. Caused by: [java.lang.reflect.InvocationTargetException - null]",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.41201.4.4.1.bbdd04c8a791124a7a6dc03455718b896ac55eb7f114e73e4c39ae6b6be5d69c.1869179c5f^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-11-11T16:10:59.133+01:00"
        }
    ]

**Comment by OmarLorenzini** [comment]
potete riprovare??

**Comment by OmarLorenzini** [comment]
Buon pomeriggio ci risulta che state utilizzando un cf che non è quello concordato da Regione Toscana ( MNTMRA03M71C615V ) ci risulta che voi state utilizzando PSCRNI82B64A952I

**Comment by SonnyMate** [comment]
Faccio subito una prova, ma questo controllo è troppo restrittivo. Non penso abbiate tutti i medici delle altre regioni nella vostra anagrafica...

**Comment by SonnyMate** [comment]
Mi pare sia lo stesso errore
        
        {
            "eventType": "PUBLICATION",
            "eventDate": "2024-11-13T14:27:07.541+01:00",
            "eventStatus": "SUCCESS",
            "identificativoDocumento": "2.16.840.1.113883.2.9.2.41.4.4^IKIS-LAB-PDFCDA2_100000000001",
            "subject": "PROVAX00X00X000Y^^^&2.16.840.1.113883.2.9.4.3.2&ISO",
            "tipoAttivita": "ERP",
            "organizzazione": "041",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.41201.4.4.1.bbdd04c8a791124a7a6dc03455718b896ac55eb7f114e73e4c39ae6b6be5d69c.27493a346f^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "traceId": "d66ac2cf59eb40ef",
            "issuer": "integrity:S2#041#PABOLZANOTEST",
            "expiringDate": "2025-11-13T14:27:07.603+01:00"
        },
        {
            "eventType": "SEND_TO_INI",
            "eventDate": "2024-11-13T14:28:08.752+01:00",
            "eventStatus": "BLOCKING_ERROR",
            "message": "SEVERITY:urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:ErrorERROR_CODE:XDSRegistryErrorCODE CONTEXT:Parallel processing failed for number 0. Exchange[ID-rt-sanita-tc11-s1-rtpc-sct-toscana-it-48875-1731340156422-2-492]. Caused by: [java.lang.reflect.InvocationTargetException - null]",
            "workflowInstanceId": "2.16.840.1.113883.2.9.2.41201.4.4.1.bbdd04c8a791124a7a6dc03455718b896ac55eb7f114e73e4c39ae6b6be5d69c.27493a346f^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
            "expiringDate": "2025-11-13T14:28:08.817+01:00"
        }

**Comment by OmarLorenzini** [comment]
buon pomeriggio ci risulta che avete mandato sempre nel campo authorPerson” il CF
 “VVNMSM75B01A703D 

 

2024-11-13 14:28:08,285 WARN  [Camel (camel-2) thread #21 - Multicast] logging.LogUtils (LogUtils.java:449) - 31340156422-2-485 - routeCallRFC249RicercaXCodice - Interceptor for {http://rfc249.client.fseinterop.sisorchestrator.regione.toscana.it/}Rfc249Client has thrown exception, unwinding now

org.apache.cxf.interceptor.Fault: Could not send Message.

              at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:64)

 

Caused by: java.net.SocketTimeoutException: SocketTimeoutException invoking[ https://wsetest.regione.toscana.it/gianov4web/rfc249rest/persona/codice/cf?codice=VVNMSM75B01A703D&stato&ctx](https://wsetest.regione.toscana.it/gianov4web/rfc249rest/persona/codice/cf?codice=VVNMSM75B01A703D&stato&ctx): Read timed out

              at sun.reflect.GeneratedConstructorAccessor337.newInstance(Unknown Source)

              at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

              at java.lang.reflect.Constructor.newInstance(Constructor.java:526)

              at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.mapException(HTTPConduit.java:1377)

              at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1361)

              at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)

              at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:651)

              at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:62)




vi chiedo di provare con PROVAX00X00X000Y

**Comment by vigliottim** [comment]
Buongiorno @SonnyMate,
chiediamo gentilmente di dare un riscontro alla regione Toscana.
Grazie.

**Comment by vigliottim** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri, procediamo alla chiusura della presente issue.
Sarà possibile riaprirla nel caso fosse necessario ulteriore supporto. Grazie.
