### ISSUE TITLE
Problemi con Gateway di test offline

### ISSUE THREAD

**Issue by g-polverini** [ministero-salute/it-fse-support#578]
Buongiorno,
mesi fa ho utilizzato senza problemi il gateway https://github.com/ministero-salute/it-fse-gtw-test-container , ma ora non mi funziona né su una macchina dove ho aggiornato il repository, né su una in cui l'ho scaricato da zero.
Nel primo caso, le risposte dall'endpoint della validazione (inviavo una LDO) erano tutte del tipo
```
{
  "traceID": "4f1132cfab3faae8",
  "spanID": "4f1132cfab3faae8",
  "type": "/msg/validator",
  "title": "Errore di validazione",
  "detail": "Nessun engine disponibile",
  "status": 400,
  "instance": "/cda-validation",
  "workflowInstanceId": "2.16.840.1.113883.2.9.2.120.4.4.46a41df0ab0514f11c0811056832c3225e06c8e11824f27c7e5517ca5cfc57fe.e0dfb49ad0^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
}
```

Faccio notare che invece inviando gli stessi dati a https://modipa-val.fse.salute.gov.it/govway/rest/in/FSE/gateway/v1 funziona tutto senza problemi.

Ho provato a seguire le istruzioni all'indirizzo https://github.com/ministero-salute/it-fse-gtw-test-container?tab=readme-ov-file#troubleshooting ma non ha sortito effetto. Alla fine ho rimosso tutto dai container, immagini e volumi, compresi altri container che utilizzo, poi ho disinstallato docker, reinstallata l'ultima versione, e riscaricato il progetto.
Ora al `docker-compose up` ho l'errore `dependency failed to start: container it-fse-container-full-it-fse-srv-log-ingestion-1 is unhealthy`, e non riesco a proseguire.

Nel secondo caso, ho l'errore come inizialmente nell'altra macchina.
Questo si verifica anche con i test contenuti nel repository.

L'api search-events-log mi restituisce questo:
```
{
  "entity": [
    {
      "log_type": "control-structured-log",
      "message": "Unknown CodeSystems found during the validation: [2.16.840.1.113883.6.96]",
      "operation": "VAL-TERMINOLOGY-CDA2",
      "op_result": "WARN",
      "op_timestamp_start": "2024-01-24T08:09:21.043+00:00",
      "op_timestamp_end": "2024-01-24T08:09:21.044+00:00",
      "gateway_name": "mocked-gateway",
      "op_warning": "WARNING",
      "op_warning_description": "Code Unknown",
      "microservice_name": "gtw-validator",
      "workflow_instance_id": "2.16.840.1.113883.2.9.2.120.4.4.46a41df0ab0514f11c0811056832c3225e06c8e11824f27c7e5517ca5cfc57fe.018a23b183^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
    },
    {
      "log_type": "control-structured-log",
      "message": "Nessun engine disponibile 2.16.840.1.113883.2.9.2.120.4.4.46a41df0ab0514f11c0811056832c3225e06c8e11824f27c7e5517ca5cfc57fe.018a23b183^^^^urn:ihe:iti:xdw:2013:workflowInstanceId",
      "operation": "VAL-CDA2",
      "op_result": "KO",
      "op_timestamp_start": "2024-01-24T08:09:21.017+00:00",
      "op_timestamp_end": "2024-01-24T08:09:21.656+00:00",
      "op_error": "KO-VAL",
      "op_error_description": "Errore nella validazione del CDA",
      "op_issuer": {
        "rawValue": "integrity:S1#190201234567XX",
        "region": "190"
      },
      "op_locality": {
        "rawValue": "201123456",
        "aslCode": "201",
        "structure": "123456"
      },
      "op_document_type": "Lettera di dimissione ospedaliera",
      "op_role": "AAS",
      "op_fiscal_code": "UNDEFINED_SUBJECT",
      "gateway_name": "mocked-gateway",
      "microservice_name": "gtw-dispatcher",
      "op_subj_application": {
        "subject_application_id": "GTW",
        "subject_application_vendor": "GATEWAY",
        "subject_application_version": "R2"
      },
      "workflow_instance_id": "2.16.840.1.113883.2.9.2.120.4.4.46a41df0ab0514f11c0811056832c3225e06c8e11824f27c7e5517ca5cfc57fe.018a23b183^^^^urn:ihe:iti:xdw:2013:workflowInstanceId"
    }
  ]
}
```

Entrambe le macchine sono Windows11.

Grazie

**Comment by vigliottim** [comment]
Buonasera, potrebbe cortesemente allegare la request utilizzata per i test? Grazie.

**Comment by g-polverini** [comment]
Una richiesta è proprio quella nella cartella Tests del progetto del gateway, vedere https://github.com/ministero-salute/it-fse-gtw-test-container/tree/main/tests

Allego comunque una richiesta di validazione fatta anche con un file generato dal software.
[dump0.txt](https://github.com/ministero-salute/it-fse-support/files/14041798/dump0.txt)
Il risultato è lo stesso in entrambi i casi

**Comment by vigliottim** [comment]
Buonasera, grazie per la segnalazione. 
Sono stati eseguiti dei merge mancanti sul repository ed ora il container funziona anche offline. 
La preghiamo di riprovare, restiamo in attesa di un suo riscontro. 
Grazie.

**Comment by g-polverini** [comment]
Buonasera,
ho scaricato il repository da zero e seguito le istruzioni per generare i file per mongo, ma purtroppo lanciando docker-compose ottengo sempre l'errore
`dependency failed to start: container gtw-full-mongo-1 is unhealthy`

**Comment by vigliottim** [comment]
Buongiorno, sono state eseguite delle fix correttive sui container e sui microservizi. 
La invitiamo a riprovare. 
Grazie.

**Comment by g-polverini** [comment]
Buongiorno,
continuo a riscontrare alcuni errori errori. Nella shell ho, tra gli altri,
```
it-fse-gtw-ini-client-1              | 2024-02-27 07:49:32.025 ERROR [gtw-ini-client,trace:  span: , parent:  exportable: ,] Error while initialiting INI context :
it-fse-gtw-ini-client-1              | java.io.FileNotFoundException: classpath:test-store/custom_truststore_new.p12 (No such file or directory)
it-fse-gtw-ini-client-1              |  at java.base/java.io.FileInputStream.open0(Native Method)
```
Delle chiamate al gateway attraverso i test forniti, alcune funzionano, altre danno errore. A volte la risposta è un po' lenta.
Ad esempio la validazione della LDO funziona, ma la pubblicazione no: oltre a lamentare il fatto che il file pdf non è segnato (ma quello è un problema dei dati), eseguendo la chiamata all'endpoint della verifica dello stato della transazione ho:
```
HTTP/1.1 500 
Content-Disposition: inline;filename=f.txt
Content-Type: application/problem+json
Transfer-Encoding: chunked
Date: Tue, 27 Feb 2024 08:16:38 GMT
Connection: close

{
  "traceID": "8fa18fa2fe5f6bba",
  "spanID": "8fa18fa2fe5f6bba",
  "type": "/msg/generic-error",
  "title": "Errore generico.",
  "detail": "Errore durante l'invocazione dell' API call search event by wii.",
  "status": 500,
  "instance": ""
}
```

Questo per lo meno con il container full.

**Comment by g-polverini** [comment]
Aggiungo che con il container lite ho meno problemi, non ho errori durante l-inizializzazione di it-fse-gtw-ini-client-1.
Però ho ugualmente l'errore nella richiesta di verifica di transazione. Questo il trace nella shell:
```
it-fse-gtw-dispatcher-1           | 2024-02-27 08:30:10.322 ERROR [gtw-dispatcher,trace:  span: , parent:  exportable: ,] Errore durante l'invocazione dell' API call search event by wii.
it-fse-gtw-dispatcher-1           | java.lang.IllegalArgumentException: Not enough variable values available to expand '{creation.response.body.workflowInstanceId'
it-fse-gtw-dispatcher-1           |     at org.springframework.web.util.UriComponents$VarArgsTemplateVariables.getValue(UriComponents.java:370)
it-fse-gtw-dispatcher-1           |     at org.springframework.web.util.UriComponents.expandUriComponent(UriComponents.java:263)
it-fse-gtw-dispatcher-1           |     at org.springframework.web.util.HierarchicalUriComponents$PathSegmentComponent.expand(HierarchicalUriComponents.java:995)
it-fse-gtw-dispatcher-1           |     at org.springframework.web.util.HierarchicalUriComponents.expandInternal(HierarchicalUriComponents.java:440)
it-fse-gtw-dispatcher-1           |     at org.springframework.web.util.HierarchicalUriComponents.expandInternal(HierarchicalUriComponents.java:53)
it-fse-gtw-dispatcher-1           |     at org.springframework.web.util.UriComponents.expand(UriComponents.java:172)
it-fse-gtw-dispatcher-1           |     at org.springframework.web.util.DefaultUriBuilderFactory$DefaultUriBuilder.build(DefaultUriBuilderFactory.java:403)
it-fse-gtw-dispatcher-1           |     at org.springframework.web.util.DefaultUriBuilderFactory.expand(DefaultUriBuilderFactory.java:154)
it-fse-gtw-dispatcher-1           |     at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:710)
it-fse-gtw-dispatcher-1           |     at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:361)
it-fse-gtw-dispatcher-1           |     at it.finanze.sanita.fse2.ms.gtw.dispatcher.client.impl.StatusCheckClient.callSearchEventByWorkflowInstanceId(StatusCheckClient.java:45)
it-fse-gtw-dispatcher-1           |     at it.finanze.sanita.fse2.ms.gtw.dispatcher.service.impl.TransactionInspectSRV.callSearchEventByWorkflowInstanceId(TransactionInspectSRV.java:30)
it-fse-gtw-dispatcher-1           |     at it.finanze.sanita.fse2.ms.gtw.dispatcher.controller.impl.TransactionInspectCTL.getEvents(TransactionInspectCTL.java:50)
it-fse-gtw-dispatcher-1           |     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
it-fse-gtw-dispatcher-1           |     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
it-fse-gtw-dispatcher-1           |     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
it-fse-gtw-dispatcher-1           |     at java.base/java.lang.reflect.Method.invoke(Method.java:568)
it-fse-gtw-dispatcher-1           |     at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
it-fse-gtw-dispatcher-1           |     at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
it-fse-gtw-dispatcher-1           |     at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
it-fse-gtw-dispatcher-1           |     at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
it-fse-gtw-dispatcher-1           |     at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
it-fse-gtw-dispatcher-1           |     at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
it-fse-gtw-dispatcher-1           |     at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1070)
it-fse-gtw-dispatcher-1           |     at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
it-fse-gtw-dispatcher-1           |     at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
it-fse-gtw-dispatcher-1           |     at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
it-fse-gtw-dispatcher-1           |     at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
it-fse-gtw-dispatcher-1           |     at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
it-fse-gtw-dispatcher-1           |     at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
it-fse-gtw-dispatcher-1           |     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
it-fse-gtw-dispatcher-1           |     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
it-fse-gtw-dispatcher-1           |     at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
it-fse-gtw-dispatcher-1           |     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
it-fse-gtw-dispatcher-1           |     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
it-fse-gtw-dispatcher-1           |     at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
it-fse-gtw-dispatcher-1           |     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
it-fse-gtw-dispatcher-1           |     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
it-fse-gtw-dispatcher-1           |     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
it-fse-gtw-dispatcher-1           |     at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
it-fse-gtw-dispatcher-1           |     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
it-fse-gtw-dispatcher-1           |     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
it-fse-gtw-dispatcher-1           |     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
it-fse-gtw-dispatcher-1           |     at org.springframework.cloud.sleuth.instrument.web.servlet.TracingFilter.doFilter(TracingFilter.java:68)
it-fse-gtw-dispatcher-1           |     at org.springframework.cloud.sleuth.autoconfig.instrument.web.TraceWebServletConfiguration$LazyTracingFilter.doFilter(TraceWebServletConfiguration.java:131)
it-fse-gtw-dispatcher-1           |     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
it-fse-gtw-dispatcher-1           |     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
it-fse-gtw-dispatcher-1           |     at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
it-fse-gtw-dispatcher-1           |     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
it-fse-gtw-dispatcher-1           |     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
it-fse-gtw-dispatcher-1           |     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
it-fse-gtw-dispatcher-1           |     at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
it-fse-gtw-dispatcher-1           |     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
it-fse-gtw-dispatcher-1           |     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
it-fse-gtw-dispatcher-1           |     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
it-fse-gtw-dispatcher-1           |     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
it-fse-gtw-dispatcher-1           |     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
it-fse-gtw-dispatcher-1           |     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
it-fse-gtw-dispatcher-1           |     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
it-fse-gtw-dispatcher-1           |     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
it-fse-gtw-dispatcher-1           |     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
it-fse-gtw-dispatcher-1           |     at org.springframework.cloud.sleuth.instrument.web.tomcat.TraceValve.invoke(TraceValve.java:90)
it-fse-gtw-dispatcher-1           |     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
it-fse-gtw-dispatcher-1           |     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
it-fse-gtw-dispatcher-1           |     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
it-fse-gtw-dispatcher-1           |     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
it-fse-gtw-dispatcher-1           |     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
it-fse-gtw-dispatcher-1           |     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
it-fse-gtw-dispatcher-1           |     at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
it-fse-gtw-dispatcher-1           |     at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
it-fse-gtw-dispatcher-1           |     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
it-fse-gtw-dispatcher-1           |     at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by vigliottim** [comment]
Buongiorno, sono state effettuate delle fix correttive.
Le facciamo presente che l'errore:
`it-fse-gtw-dispatcher-1           | java.lang.IllegalArgumentException: Not enough variable values available to expand '{creation.response.body.workflowInstanceId'`
fa parte del normale flusso di un restClient: se la chiamata precedente non va a buon fine (in tal caso, la pubblicazione con documenti non firmati), allora il wii non viene settato nella variabile utilizzata successivamnete per effettuare la ricerca tramite l'opportuno endpoint.
La invitiamo a riprovare e segnalarci se riscontra eventuali ulteriori anomalie.
Grazie.

**Comment by vigliottim** [comment]
Buonasera, non avendo ricevuto ulteriori riscontri, procediamo alla chiusura del presente ticket.
Potrà riaprirlo nel caso in cui necessiti di ulteriore supporto.
Grazie.
